### ISSUE TITLE
My contribute

### ISSUE THREAD

**Issue by farisoftfry** [weachy/CoreBookX-14-Hackintosh#1]
Hello,
I would like to help you because you are doing a great work. Even if I don't know almost anything about programming, I hope you will appreciate my help about listing some sources and tools I've found during my research, maybe you can find something useful:

Source:
https://www.freecodecamp.org/news/build-a-hackintosh/
https://www.olarila.com (very interesting)
https://www.olarila.com/topic/5676-folders-for-all-chipsets-clover-and-opencore/ (pre-made folders for chipset)
https://www.tonymacx86.com/
https://dortania.github.io/OpenCore-Install-Guide/ (...of course, open core edition)
https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/config.plist-per-hardware/coffee-lake (...of course, clover edition)

Tools:
https://github.com/corpnewt/ProperTree
https://github.com/corpnewt/MountEFI
https://github.com/Pavo-IM/OC-Gen-X

I hope this will help you!
Thanks again
Regards

**Comment by weachy** [comment]
thx for your help, really helpful. :)
