### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by matias200308** [weachy/CoreBookX-14-Hackintosh#11]
¿Alguien que haya conseguido hacer la instalación podría hacer un tutorial o dejar un enlace del tutorial que haya seguido?, estoy teniendo problemas durante la instalación. sería de mucha ayuda, gracias.

**Comment by Fernando08RF** [comment]
estoy de acuerdo, entiendo que para realizar hackintosh hay que tener cierto nivel de experiencia pero a pesar de ya ser mi tercer hackintosh se me ha vuelto muy complicado la instalación en este dispositivo

**Comment by Chiquitin29** [comment]
yo también necesito ayuda, he revisado el archivo config.plist muchas veces, lo he reescrito por completo, he realizado los cambios en la BIOS y aun así no logro hacer la instalación, lo mas lejos que he llegado a sido la barra de instalación con el logo de apple pero después se reinicia. haría falta un tutorial paso a paso, no son los mismos ajustes en todos los dispositivos.

**Comment by DiegoIslaY** [comment]
Yes please, anyone who has been successful in the installation.

**Comment by bricamac** [comment]
Yep the installation it's quiet easy to could Big Sur or Monterey create usb boot key using this tool "Install Media BS OC-V4"  (https://www.hackintosh-montreal.com/download?id=6558) .  Then on EFI partition of the usb key ;  copy the weachy EFI .  Before to boot on this new key, go to into the BIOS to modify the configuration as explained by weachy... you could boot on the usb key and install macos.
