### ISSUE TITLE
Sin bateria en windows 11

### ISSUE THREAD

**Issue by Darthside28** [weachy/CoreBookX-14-Hackintosh#12]
Hola, como siempre agradezco el tiempo y esfuerzo, actualice con los archivos que nos compartes, te comento que tengo dual boot en otra particion del mismo disco, y el efi boot lo tengo en una memoria sd, hasta antes de cambiar el efi no habia tenido situaciones extrañas, pero ahora cuando inicio windows desde opencore, en windows no aparece la bateria, como si no tuviera, y cuando inicio directamente del boot de windows si me aparece.

**Comment by weachy** [comment]
yes, my friend has the same problem (I don't have windows on my corebookX). so this battery patch is not perfect right now. I will try to figure out.

**Comment by weachy** [comment]
Fixed
