### ISSUE TITLE
網卡硬改

### ISSUE THREAD

**Issue by linuxjackie** [weachy/CoreBookX-14-Hackintosh#13]
不好意思，QQ被盗，知乎又只限於國內身份證認證，只能在這裡求問，請教一下網卡的硬改方式，謝謝

**Comment by weachy** [comment]
Taobao上面有硬改网卡服务。搜索：corebook 维奇

**Comment by linuxjackie** [comment]
謝謝回覆，可我沒在國內，寄回去改有點困難（也有打稅等等問題）。

**Comment by weachy** [comment]
有海外来买改好的成品，通过转运到海外。已经有机器的话确实不太方便，成本也高出很多，不合算

**Comment by linuxjackie** [comment]
嗯嗯，網卡我也手上有，也想問一下，可以單買套件嗎，我這邊找下人看下焊改一下
