### ISSUE TITLE
Webcam image very dark

### ISSUE THREAD

**Issue by bricamac** [weachy/CoreBookX-14-Hackintosh#16]
Hi,

May you tell me how I could fix the image from the webcam is very dark when I use macos system.  I didn't get this problem on windows 10 ?

Thanks in advance

**Comment by weachy** [comment]
I have no diea so far.

**Comment by farisoftfry** [comment]
that's because there is no settings on a Mac to change configuration of the webcam. Try a setting control camera app and you will solve your problem. Hope It helps. Regards

**Comment by weachy** [comment]
Try this free app: https://github.com/Itaybre/CameraController

**Comment by bricamac** [comment]
Thanks again for your help... This free app works fine !!!
