### ISSUE TITLE
Update EFI folder

### ISSUE THREAD

**Issue by farisoftfry** [weachy/CoreBookX-14-Hackintosh#17]
Hello,
I would like to try to update your EFI folder to OpenCore 0.7.6 and every kext, ACPI, Drivers etc...
I thought to use this software to update everything https://github.com/ic005k/QtOpenCoreConfig but I'm aware to lose some customizations/corrections you did to "stock" files.
Have you already used that software? Otherwise, what do you use to update everything without losing your customizations?
Or if you think it is better to do it in manual way, can you list the differences from the stock files?
Thanks for your help.
Regards

**Comment by weachy** [comment]
OCAT is safe to use, but I prefer to update manually.
