### ISSUE TITLE
New update problema with patch battery

### ISSUE THREAD

**Issue by luca79rio** [weachy/CoreBookX-14-Hackintosh#18]
In the new update, the battery patch in windows 11 has solved the problem of the missing icon, in Macos the patch works badly the state of charge is not detected immediately.

**Comment by farisoftfry** [comment]
hello, yes, I agree. Even more from the update os says that my battery need assistance because battery's power dropped

**Comment by farisoftfry** [comment]
It doesn't go to sleep too, after update, when you close the lid, with or without ac adapter plugged in.

**Comment by weachy** [comment]
Fixed
