### ISSUE TITLE
Battery works better with last update but there is still some problems...

### ISSUE THREAD

**Issue by farisoftfry** [weachy/CoreBookX-14-Hackintosh#20]
Hello,
first of all thanks for your hard work!
I've already tested your latest version of EFI and battery works lot better, it recognize when it is plugged in or not etc...
But my battery settings still shows what my battery need assistance and it seems I did more than 400 cycles of charges. That's impossible, of course. And I think there is a mistake with battery capacity.
I attach a screenshot of coconut battery
![battery](https://user-images.githubusercontent.com/30302285/148127113-08573576-ffef-4be3-88ea-a0c012ec921c.png)
Hope it helps, regards

**Comment by weachy** [comment]
Can't do more at the moment as EC is not fully working

**Comment by farisoftfry** [comment]
Hello, I tried to update OpenCore files, drivers, config and kexts with OcAuxiliaryTools (latest version for OpenCore 0.7.8) but then the touchpad doesn't work anymore. Any tip/help?
Thanks
Regards

**Comment by weachy** [comment]
Have you ever changed VoodooPS2 kext?

**Comment by farisoftfry** [comment]
no, I've just updated your working Efi folder with OcAuxiliaryTools...I don't have so many knowledge to change VoodooPS2 kext...I attach the image of updates found from OcAuxiliaryTools. Maybe I have an idea: is is possible that when I click on "check for updates" it downloads all kexts from the net again and vanish your changes? It shouldn't but it is the only thing that for me has a sense...or it change the config in an inappropriate way...I don't know
Thanks for your help
![Schermata 2022-02-17 alle 09 40 39](https://user-images.githubusercontent.com/30302285/154438474-24970bb6-5767-4243-b292-92a0878a99c1.png)

**Comment by farisoftfry** [comment]
update: I was able to upgrade to 0.7.8 deselecting everything on the left side a part the ones with red squares. So now everything should be updated and it seems that everything works well
