### ISSUE TITLE
Figure out how to identify the new model of CoreBook X 14

### ISSUE THREAD

**Issue by terminet85** [weachy/CoreBookX-14-Hackintosh#21]
Thank you for your great work!
I've just bought one CoreBook X i5-8259U. I've read your waning. So can I check what version I have?
Thanks

**Comment by weachy** [comment]
You can easily judge by the color of the motherboard. 
Green motherboard --> new.

**Comment by terminet85** [comment]
> You can easily judge by the color of the motherboard.
> Green motherboard --> new.
> Black motherboard --> old.

Thank you for your reply! There is another solution? I don’t wanna to open it now… 😩

**Comment by terminet85** [comment]
Okay sorted out I got a new green motherboard version I'll open a new 3d, thanks.

**Comment by weachy** [comment]
I realize the SN of new model notebook is starting with "JCorBX". As a comparison, the old one is starting with "CBookX"

**Comment by Anycubic** [comment]
Hello, just bought a JCorBX model as well. Unfortunately this was supposed to be my first OpenCore attempt so I can only help by testing. Audio chip seems the same as old model (Realtek), so maybe it is fixable, don't know about battery.
