### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by rboldini** [weachy/CoreBookX-14-Hackintosh#26]
Just an advice to tell you that my work is now under GNU v.3 license.

It will be still Open Source.
But now you need to reference my work.

In your case I found that SSDT-LID-AC 
and SSDT-BATT are sold as 'Hard work' from your group this goes against any open source ethics.

So please contribute to the work of others.

**Comment by weachy** [comment]
SSDT-LID-AC and SSDT-BATT contributed by @maguag , I mean no offense. Sorry for my recklessness,  I will add your reference and thank u for your hard work. BTW, I'm charging someone to solder a Broadcom wireless card, this EFI is always free to use.
