### ISSUE TITLE
Sin audio en adaptador usb-c, usando jack 3.5, or hdmi

### ISSUE THREAD

**Issue by Darthside28** [weachy/CoreBookX-14-Hackintosh#27]
Hola buenas noches, compre un adaptador para el puerto usb-c que incluye entre otros puertos una salida hdmi y jack 3.5 para audifonos, en ninguno de estos puertos sale audio, si funcionan el resto de los puertos, habra alguna solución?

**Comment by weachy** [comment]
I think u should change output channel

**Comment by Darthside28** [comment]
Muchas gracias por tu respuesta, busque en el panel de preferencias, audio, y no aparece opción para elegir otra salida de audio.

**Comment by weachy** [comment]
I don't have a USB Type-C hub with a 3.5mm headphone jack. I have tested the HDMI audio works fine.
