### ISSUE TITLE
Modificaciones a realizar en la corebook x?

### ISSUE THREAD

**Issue by matias200308** [weachy/CoreBookX-14-Hackintosh#3]
Hola, antes de iniciar el proceso de hackintosh 
¿Cuáles son las modificaciones recomendadas a hacer en la BIOS? 
¿la memoria ssd requiere alguna modificación? 
¿Cuál es el método de hackintosh a utilizar? intente utilizando el manual de  Dortania pero no funcionó

**Comment by weachy** [comment]
added bios settings in README.md
