### ISSUE TITLE
风扇异常，跟oc的配置有关吗？

### ISSUE THREAD

**Issue by zepang** [weachy/CoreBookX-14-Hackintosh#31]
风扇一开机就开始刮刮转，就算不开任何应用程序也一直转

**Comment by Fernando08RF** [comment]
a mi no me ocurre, si bien los ventiladores se encienden al iniciar se detienen en menos de 10 segundos

**Comment by weachy** [comment]
开机需要加载大量系统进程，稳定后会恢复平静
