### ISSUE TITLE
FaceTime y Mensajes no funciona

### ISSUE THREAD

**Issue by Fernando08RF** [weachy/CoreBookX-14-Hackintosh#32]
hace poco actualice la carpeta EFI usando la de este sitio como siempre, pero al hacerlo FaceTime y mensajes dejaron de funcionar, ya he intentado todo lo que sugiere la guía de opencore pero sin buenos resultados.
Necesito poder usar FaceTime por temas de estudios

**Comment by weachy** [comment]
Generate your own MLB, UUID and Serial number. This would help : https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

**Comment by Fernando08RF** [comment]
> Generate your own MLB, UUID and Serial number. This would help : https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

Ya hice todo eso, muchas veces, como dije anteriormente no tenia problemas para usar FaceTime antes de actualizar el efi (reemplace el numero de serie y los demás datos como siempre)
