### ISSUE TITLE
corebook x won't turn on

### ISSUE THREAD

**Issue by matias200308** [weachy/CoreBookX-14-Hackintosh#33]
This has nothing to do with the operating system but I would like to know if someone can help me with this problem.
my computer stopped working out of nowhere, it turns on the power light but there is no image, it also makes a small sound as if it turned on but it stops immediately
There are occasions when the light turns on and off, but the screen never turns on.

**Comment by weachy** [comment]
I suggest that you should contact the customer service ASAP.
