### ISSUE TITLE
logo进度条界面出现一闪而过的花屏和砰的爆声

### ISSUE THREAD

**Issue by zepang** [weachy/CoreBookX-14-Hackintosh#34]

**Comment by weachy** [comment]
花屏的瞬间是加载核显驱动所致。爆音应该与bios设定或扬声器固件层有关。

**Comment by zepang** [comment]
所以目前来看没有方法解决吗？

**Comment by weachy** [comment]
闪一下花屏在黑果本上普遍存在，似乎没有见过尝试解决的；
爆音在很多大厂（例如联想、戴尔）的笔记本机型也存在，有的win下也开机爆音，当然修改一下bios应该是有希望解决的。我目前用下来越来越觉得影响可以忽略不计了（基本只在开关机和休眠唤醒时产生）。
