### ISSUE TITLE
No es un problema, es una solicitud.

### ISSUE THREAD

**Issue by Darthside28** [weachy/CoreBookX-14-Hackintosh#36]
Hola buenas tardes, actualice mi corebook a monterey 12.6 y todo ok, veo que hay actualizaciones en diferentes kext y en la version del opencore, estas considerando actualizarlos?.

Agradezco tu respuesta.
Saludos.

**Comment by weachy** [comment]
Y, I will update EFI before Apple release macOS Ventura.

**Comment by Darthside28** [comment]
Excelente noticia, estaré al pendiente.

**Comment by weachy** [comment]
updated  :)
