### ISSUE TITLE
Actualizacion a 13.3.1, saber si es seguro actualizar?

### ISSUE THREAD

**Issue by Darthside28** [weachy/CoreBookX-14-Hackintosh#46]
Antes que nada, agradezco la atención que siempre pones a este proyecto, sera seguro actualizar a 13.3.1?, y otra duda, la bateria de mi corebook x se daño y tuve que reemplazarla, sabes si este fallo pudiera estar relacionado a la utilizacion de macos en este equipo??, o es una falla de harware exclusivamente?.

**Comment by weachy** [comment]
You can safely update to 13.3.1. A lot of people have had battery issues, whether using macOS or windows.
