### ISSUE TITLE
Ayuda sin Bluetooth 

### ISSUE THREAD

**Issue by Darthside28** [weachy/CoreBookX-14-Hackintosh#47]
Actualicé a 13.4 y me quedé sin Bluetooth, me podrías ayudar?, Te agradezco de antemano.

**Comment by weachy** [comment]
First, you should update BlueToolFixup.kext to V2.6.7, here is a pre-build link: https://github.com/zxystd/BrcmPatchRAM/actions/runs/5117839588.

Then open your config.plist, add this NVRAM args under '7C436110-AB2A-4BBB-A880-FE41995C9F82':
Key：bluetoothInternalControllerInfo，Value：0000000000000000000000000000，Type：DATA
Key：bluetoothExternalDongleFailed，Value：00，Type：DATA

Take effect after reboot.

**Comment by Darthside28** [comment]
Muchas gracias por la informaciòn segui tus instrucciones y funciono correctamente, saludos...
